# Dockerfile

# Use the prepared base image
FROM agrigorev/zoomcamp-model:mlops-2024-3.10.13-slim

RUN pip install -U pip
RUN pip install pipenv

WORKDIR /app

COPY [ "Pipfile", "Pipfile.lock", "./" ]

RUN pipenv install --system --deploy

COPY score.py /app/score.py

RUN mkdir output

CMD ["python", "score.py", "--year", "2023", "--month", "4"]